// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EventMessage.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "EventMessage.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace WeWrite {

namespace {

const ::google::protobuf::Descriptor* EventMessage_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  EventMessage_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_EventMessage_2eproto() {
  protobuf_AddDesc_EventMessage_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "EventMessage.proto");
  GOOGLE_CHECK(file != NULL);
  EventMessage_descriptor_ = file->message_type(0);
  static const int EventMessage_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(EventMessage, s_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(EventMessage, participantid_),
  };
  EventMessage_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      EventMessage_descriptor_,
      EventMessage::default_instance_,
      EventMessage_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(EventMessage, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(EventMessage, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(EventMessage));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_EventMessage_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    EventMessage_descriptor_, &EventMessage::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_EventMessage_2eproto() {
  delete EventMessage::default_instance_;
  delete EventMessage_reflection_;
}

void protobuf_AddDesc_EventMessage_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\022EventMessage.proto\022\007WeWrite\"0\n\014EventMe"
    "ssage\022\t\n\001s\030\001 \002(\t\022\025\n\rparticipantID\030\002 \002(\t", 79);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "EventMessage.proto", &protobuf_RegisterTypes);
  EventMessage::default_instance_ = new EventMessage();
  EventMessage::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_EventMessage_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_EventMessage_2eproto {
  StaticDescriptorInitializer_EventMessage_2eproto() {
    protobuf_AddDesc_EventMessage_2eproto();
  }
} static_descriptor_initializer_EventMessage_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int EventMessage::kSFieldNumber;
const int EventMessage::kParticipantIDFieldNumber;
#endif  // !_MSC_VER

EventMessage::EventMessage()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void EventMessage::InitAsDefaultInstance() {
}

EventMessage::EventMessage(const EventMessage& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void EventMessage::SharedCtor() {
  _cached_size_ = 0;
  s_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  participantid_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

EventMessage::~EventMessage() {
  SharedDtor();
}

void EventMessage::SharedDtor() {
  if (s_ != &::google::protobuf::internal::kEmptyString) {
    delete s_;
  }
  if (participantid_ != &::google::protobuf::internal::kEmptyString) {
    delete participantid_;
  }
  if (this != default_instance_) {
  }
}

void EventMessage::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* EventMessage::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return EventMessage_descriptor_;
}

const EventMessage& EventMessage::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_EventMessage_2eproto();
  return *default_instance_;
}

EventMessage* EventMessage::default_instance_ = NULL;

EventMessage* EventMessage::New() const {
  return new EventMessage;
}

void EventMessage::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (has_s()) {
      if (s_ != &::google::protobuf::internal::kEmptyString) {
        s_->clear();
      }
    }
    if (has_participantid()) {
      if (participantid_ != &::google::protobuf::internal::kEmptyString) {
        participantid_->clear();
      }
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool EventMessage::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required string s = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_s()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->s().data(), this->s().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(18)) goto parse_participantID;
        break;
      }

      // required string participantID = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_participantID:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_participantid()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->participantid().data(), this->participantid().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void EventMessage::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required string s = 1;
  if (has_s()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->s().data(), this->s().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      1, this->s(), output);
  }

  // required string participantID = 2;
  if (has_participantid()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->participantid().data(), this->participantid().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      2, this->participantid(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* EventMessage::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required string s = 1;
  if (has_s()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->s().data(), this->s().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->s(), target);
  }

  // required string participantID = 2;
  if (has_participantid()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->participantid().data(), this->participantid().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->participantid(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int EventMessage::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required string s = 1;
    if (has_s()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->s());
    }

    // required string participantID = 2;
    if (has_participantid()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->participantid());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void EventMessage::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const EventMessage* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const EventMessage*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void EventMessage::MergeFrom(const EventMessage& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_s()) {
      set_s(from.s());
    }
    if (from.has_participantid()) {
      set_participantid(from.participantid());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void EventMessage::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void EventMessage::CopyFrom(const EventMessage& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool EventMessage::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000003) != 0x00000003) return false;

  return true;
}

void EventMessage::Swap(EventMessage* other) {
  if (other != this) {
    std::swap(s_, other->s_);
    std::swap(participantid_, other->participantid_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata EventMessage::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = EventMessage_descriptor_;
  metadata.reflection = EventMessage_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace WeWrite

// @@protoc_insertion_point(global_scope)
